// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Trong tháng 9 năm 1740, tình trạng bất ổn bắt đầu nổi lên từ các cụm dân cư gốc Hoa, chúng được châm ngòi từ hoạt động đàn áp của chính phủ và thu nhập giảm do giá đường sụt giảm trước khi diễn ra vụ thảm sát.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/57/Chinezenmoord_van_stolk_%282%29.jpg",
                            Price = 99.99m,
                            Title = "Thảm sát Batavia năm 1740"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hiện tượng 2012 bao gồm hàng loạt những người tin về thuyết mạt thế cho rằng vào ngày 21 tháng 12 năm 2012 là ngày tận thế hoặc sẽ xảy ra những sự kiện biến đổi lớn",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7a/East_side_of_stela_C%2C_Quirigua.PNG",
                            Price = 99.99m,
                            Title = "Hiện tượng 2012"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Trung Bộ châu Mỹ cổ đại (thuật ngữ gốc: Mesoamerica) là 1 vùng và là 1 khu vực văn hóa ở châu Mỹ, trải dài từ miền trung México đến Belize, Guatemala, El Salvador, Honduras, Nicaragua và miền bắc Costa Rica",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/79/Mesoamerica_english.PNG",
                            Price = 99.99m,
                            Title = "Trung Bộ châu Mỹ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
